# Generated by Django 5.1.1 on 2024-10-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=30),
        ),
    ]
