# Generated by Django 5.1.1 on 2024-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.TextField(default='Please Modify and Change my Style'),
        ),
    ]
