# Generated by Django 5.1.1 on 2024-10-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledvideo',
            name='platform',
        ),
        migrations.AddField(
            model_name='scheduledvideo',
            name='platforms',
            field=models.ManyToManyField(default='youtube', to='core.platform'),
        ),
    ]
