# Generated by Django 5.1.1 on 2024-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_template_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='left_margin',
            field=models.IntegerField(default=270),
        ),
        migrations.AlterField(
            model_name='template',
            name='right_margin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_margin',
            field=models.IntegerField(default=960),
        ),
    ]
