# Generated by Django 5.1.1 on 2024-11-13 05:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platform_remove_scheduledvideo_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='template',
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
