# Generated by Django 5.1.1 on 2024-10-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_template_left_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voices_id',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
