# Generated by Django 5.1.1 on 2024-10-11 23:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_voices_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('preview_url', models.CharField(max_length=100)),
                ('image_url', models.URLField(null=True)),
                ('api_voice_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
