# Generated by Django 5.1.1 on 2024-10-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_voicetier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicetier',
            old_name='api_voice_id',
            new_name='voice_id',
        ),
    ]
