# Generated by Django 5.1.1 on 2024-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_api_voice_id_voicetier_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetier',
            name='price',
            field=models.IntegerField(default=4),
        ),
    ]
